# spring.datasource.url=jdbc:h2:mem:test
spring:
  datasource:
    url: jdbc:h2:file:./h2data
    driverClassName: org.h2.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    root: info
    com.hef.blog: debug




